version: 2
updates:
- package-ecosystem: "gradle"
  directories:
    - "/"
    - "/conformance-test-framework"
    - "/usage-demo"
  schedule:
    interval: "daily"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
